name: Publish package - scala-lint-format
run-name: Published maven package for 'scala-lint-format' - '${{ github.ref }}'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'sbt'

      - name: list
        run: ls -la

      - name: Set up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.2

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: sbt publish
